// Generated by generate-keys, DO NOT EDIT

#include <types.h>

typedef enum {
    SPECIAL_KEY_START = 128,

    KEY_TAB = 0x80,
    KEY_LEFT_SHIFT = 0x81,
    KEY_RIGHT_SHIFT = 0x82,
} Key;

extern u8 KEY_TABLE[94];
